export const heroes = {
    "Adam Warlock": {
        gender: 'Male',
        role: 'Strategist',
        difficulty: 3,
        eyeColor: 'White',
        hair: 'Gold',
    },
    "Black Panther": {
        gender: 'Male',
        role: 'Duelist',
        difficulty: 4,
        eyeColor: 'Brown',
        hair: 'Brown',
    },
    "Black Widow": {
        gender: 'Female',
        role: 'Duelist',
        difficulty: 4,
        eyeColor: 'Blue',
        hair: 'Red',
    },
    "Captain America": {
        gender: 'Male',
        role: 'Vanguard',
        difficulty: 2,
        eyeColor: 'Blue',
        hair: 'Blonde',
    },
    "Cloak": {
        gender: 'Male',
        role: 'Strategist',
        difficulty: 3,
        eyeColor: 'Gray',
        hair: 'Black',
    },
    "Dagger": {
        gender: 'Female',
        role: 'Strategist',
        difficulty: 3,
        eyeColor: 'Blue',
        hair: 'Blonde',
    },
    "Doctor Strange": {
        gender: 'Male',
        role: 'Vanguard',
        difficulty: 2,
        eyeColor: 'Green',
        hair: 'Brown',
    },
    "Groot": {
        gender: 'Male',
        role: 'Vanguard',
        difficulty: 2,
        eyeColor: 'Green',
        hair: 'N/A',
    },
    "Hawkeye": {
        gender: 'Male',
        role: 'Duelist',
        difficulty: 4,
        eyeColor: 'Green',
        hair: 'Blonde',
    },
    "Hela": {
        gender: 'Female',
        role: 'Duelist',
        difficulty: 3,
        eyeColor: 'Green',
        hair: 'N/A',
    },
    "Bruce Banner": {
        gender: 'Male',
        role: 'Vanguard',
        difficulty: 4,
        eyeColor: 'Brown',
        hair: 'Brown',
    },
    "Hulk": {
        gender: 'Male',
        role: 'Vanguard',
        difficulty: 4,
        eyeColor: 'Green',
        hair: 'Black',
    },
    "Invisible Woman": {
        gender: 'Female',
        role: 'Strategist',
        difficulty: 4,
        eyeColor: 'Blue',
        hair: 'Blonde',
    },
    "Iron Fist": {
        gender: 'Male',
        role: 'Duelist',
        difficulty: 4,
        eyeColor: 'Brown',
        hair: 'Black',
    },
    "Iron Man": {
        gender: 'Male',
        role: 'Duelist',
        difficulty: 2,
        eyeColor: 'Blue',
        hair: 'Brown',
    },
    "Jeff the Land Shark": {
        gender: 'Male',
        role: 'Strategist',
        difficulty: 1,
        eyeColor: 'Black',
        hair: 'N/A',
    },
    "Loki": {
        gender: 'Male',
        role: 'Strategist',
        difficulty: 4,
        eyeColor: 'Green',
        hair: 'Black',
    },
    "Luna Snow": {
        gender: 'Female',
        role: 'Strategist',
        difficulty: 2,
        eyeColor: 'Blue',
        hair: 'Black',
    },
    "Magik": {
        gender: 'Female',
        role: 'Duelist',
        difficulty: 3,
        eyeColor: 'Blue',
        hair: 'Blonde',
    },
    "Magneto": {
        gender: 'Male',
        role: 'Vanguard',
        difficulty: 2,
        eyeColor: 'Blue',
        hair: 'White',
    },
    "Mantis": {
        gender: 'Female',
        role: 'Strategist',
        difficulty: 1,
        eyeColor: 'Black',
        hair: 'Black',
    },
    "Mister Fantastic": {
        gender: 'Male',
        role: 'Duelist',
        difficulty: 3,
        eyeColor: 'Brown',
        hair: 'Brown',
    },
    "Moon Knight": {
        gender: 'Male',
        role: 'Duelist',
        difficulty: 3,
        eyeColor: 'Blue',
        hair: 'N/A',
    },
    "Namor": {
        gender: 'Male',
        role: 'Duelist',
        difficulty: 2,
        eyeColor: 'Blue',
        hair: 'Blonde',
    },
    "Peni Parker": {
        gender: 'Female',
        role: 'Vanguard',
        difficulty: 3,
        eyeColor: 'Blue',
        hair: 'Black',
    },
    "Psylocke": {
        gender: 'Female',
        role: 'Duelist',
        difficulty: 5,
        eyeColor: 'Blue',
        hair: 'Purple',
    },
    "Rocket Raccoon": {
        gender: 'Male',
        role: 'Strategist',
        difficulty: 1,
        eyeColor: 'Red',
        hair: 'Brown',
    },
    "Scarlet Witch": {
        gender: 'Female',
        role: 'Duelist',
        difficulty: 1,
        eyeColor: 'Green',
        hair: 'Red',
    },
    "Spider Man": {
        gender: 'Male',
        role: 'Duelist',
        difficulty: 5,
        eyeColor: 'Hazel',
        hair: 'Brown',
    },
    "Squirrel Girl": {
        gender: 'Female',
        role: 'Duelist',
        difficulty: 1,
        eyeColor: 'Green',
        hair: 'Ginger',
    },
    "Star Lord": {
        gender: 'Male',
        role: 'Duelist',
        difficulty: 2,
        eyeColor: 'Hazel',
        hair: 'Blonde',
    },
    "Storm": {
        gender: 'Female',
        role: 'Duelist',
        difficulty: 3,
        eyeColor: 'Blue',
        hair: 'White',
    },
    "The Punisher": {
        gender: 'Male',
        role: 'Duelist',
        difficulty: 1,
        eyeColor: 'Blue',
        hair: 'Brown',
    },
    "Thor": {
        gender: 'Male',
        role: 'Vanguard',
        difficulty: 2,
        eyeColor: 'Blue',
        hair: 'Blonde',
    },
    "Venom": {
        gender: 'Male',
        role: 'Vanguard',
        difficulty: 1,
        eyeColor: 'White',
        hair: 'N/A',
    },
    "Winter Soldier": {
        gender: 'Male',
        role: 'Duelist',
        difficulty: 3,
        eyeColor: 'Blue',
        hair: 'Brown',
    },
    "Wolverine": {
        gender: 'Male',
        role: 'Duelist',
        difficulty: 3,
        eyeColor: 'Brown',
        hair: 'Black',
    },
    // "Moriah": {
    //     gender: 'Female',
    //     role: 'Kitchen',
    //     difficulty: 999,
    //     eyeColor: 'Brown',
    //     hair: 'Brown',
    // },
}